fullNameOverride: ""
nameOverride: ""

environment: dev # dev/stage/prod

# instance: # if your application is running in multiple instances, eg. pm/bm/bulder/folio
# cluster: backend  # backend/security/skybank/ent-app/pap/plattform
# domain: mydomain.no # if you need to override the domain, otherwise it will be set to the default domain of the cluster
team: "kristian-app-team"
product: "kristian-app-product"

image:
  repo: "gcr.io/google-samples/hello-app"
  tag: 1.0.0
  port: 8080

envVars:
  variables: []
    # - name: MY_ENVIRONMENT
    #   value: production
    # - name: MY_NODE_NAME
    #     valueFrom:
    #       fileRef:
    #         field: spec.nodeName
  secrets: []
    # - envVarName: MY_ENV_VAR
    #   keyVaultName: secret-vault
    #   keyVaultSecret: my-super-secret
    #   type: secret # secret/key/certificate
    #   version: xxx # versioned secret in key vault

ingress:
  enabled: true
  public: false # public or private ingress class.
  enableDnsRecord: true # Create DNS record from this ingress
  # ingressClassOverride: "" # if set will override ingressclass defined by "public" field.
  # dnsTargetOverride:  # if set will override DNS record IP with a custom value.
  #   type: A # A/CNAME
  #   target: "" # IP or CNAME, E.g. 1.2.3.4 or cluster.dns.kristian.com
  paths:
    - path: "/"
      pathType: ImplementationSpecific
      port: 8080

resources:
  memory: 256Mi
  cpu: 100m
  # memLimitOverride: "" # If not set will be the same as resources.memory

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

additionalAnnotations:
  global: {}
  deployment: {}
  pod: {}
  ingress: {}
  serviceAccount: {}
  podDisruptionBudget: {}
additionalLabels:
  global: {}
  deployment: {}
  pod:
    azure.workload.identity/use: "true"
  ingress: {}
  serviceAccount: {}
  podDisruptionBudget: {}

# Container Probes
containers:
  startupProbe:
    enabled: true
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: true

serviceAccount:
  create: true
  # If not set, defaults to nameOverride
  name: ""

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

alerts: {}
