apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kristian-app.fullname" . }}
  labels:
    {{- include "kristian-app.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels.deployment }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.additionalAnnotations.deployment }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "kristian-app.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "kristian-app.labels" . | nindent 8 }}
        {{- with .Values.additionalLabels.pod}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.additionalAnnotations.pod }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kristian-app.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ include "kristian-app.name" . }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          image: {{ include "kristian-app.image" . }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            # Graceful shutdown: wait 5 seconds before terminating the container
            preStop:
              # Can be updated in 1.34 of kubernetes to sleep directly
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 5
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- with .Values.envVars.variables }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port | default 8080 }}
              protocol: TCP
          {{- if .Values.containers.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.containers.livenessProbe.path | default "/health" }}
              port: {{ .Values.containers.livenessProbe.port | default "http" }}
            initialDelaySeconds: {{ .Values.containers.livenessProbe.initialDelaySeconds | default 2 }}
            periodSeconds: {{ .Values.containers.livenessProbe.periodSeconds | default 15 }}
            timeoutSeconds: {{ .Values.containers.livenessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.containers.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.containers.livenessProbe.failureThreshold | default 3 }}
          {{- end }}
          {{- if .Values.containers.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.containers.readinessProbe.path | default "/health" }}
              port: {{ .Values.containers.readinessProbe.port | default "http" }}
            initialDelaySeconds: {{ .Values.containers.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.containers.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.containers.readinessProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.containers.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.containers.readinessProbe.failureThreshold | default 5 }}
          {{- end }}
          {{- if .Values.containers.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.containers.startupProbe.path | default "/health" }}
              port: {{ .Values.containers.startupProbe.port | default "http" }}
            initialDelaySeconds: {{ .Values.containers.startupProbe.initialDelaySeconds | default 3 }}
            periodSeconds: {{ .Values.containers.startupProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.containers.startupProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.containers.startupProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.containers.startupProbe.failureThreshold | default 3 }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.memory | default "128Mi" }}
              cpu: {{ .Values.resources.cpu | default "20m" }}
            limits:
              memory: {{ .Values.resources.memLimitOverride | default .Values.resources.memory | default "128Mi" }}
