{{- if .Values.ingress.enabled }}
{{- $ingressClass := "" -}}
{{- if .Values.ingress.ingressClassOverride -}}
  {{- $ingressClass = .Values.ingress.ingressClassOverride -}}
{{- else if .Values.ingress.public -}}
  {{- $ingressClass = "nginx-public" -}}
{{- else -}}
  {{- $ingressClass = "nginx-private" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kristian-app.fullname" . }}
  labels:
    {{- include "kristian-app.ingressLabels" . | nindent 4 }}
    {{- if .Values.ingress.enableDnsRecord }}
    external-dns.alpha.kubernetes.io/enabled: "true"
    {{- end }}
  annotations:
    {{- include "kristian-app.ingressAnnotations" . | nindent 4 }}
    {{- if and .Values.ingress.enableDnsRecord .Values.ingress.dnsTargetOverride }}
    {{- if eq .Values.ingress.dnsTargetOverride.type "A" }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.dnsTargetOverride.target | quote }}
    {{- else if eq .Values.ingress.dnsTargetOverride.type "CNAME" }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.dnsTargetOverride.target | quote }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ $ingressClass }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.paths }}
    - host: {{ include "kristian-app.fullname" $ }}.{{ $.Values.domain | default "example.com" }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kristian-app.fullname" $ }}
                port:
                  number: {{ .port }}
    {{- end }}
{{- end }}