apiVersion: v1
kind: Service
metadata:
  name: {{ include "kristian-app.fullname" . }}
  labels:
    {{- include "kristian-app.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels.global }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.additionalAnnotations.global }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.image.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kristian-app.selectorLabels" . | nindent 4 }}
